### PR TITLE
Fix typos found in POD

### PR DESCRIPTION
**Pull request by paultcochrane**
While reading through the docs I noticed a couple of typos, which I've fixed in this patch.

### CODE REVIEW

**Comment by rizen** [comment]
How many more pull requests do you have coming? I'm going to accept them all, but I want to wait to push a release to the public until you think you might be done.

**Comment by paultcochrane** [comment]
Hi!  Very cool that you answered :-)  I've got one pull request in the pipeline (to fix podchecker warnings), but it'll conflict with the whitespace-removing patch so I was waiting to see if you merge the patch before I work on that anymore.  I had thought I could try and improve code coverage, but that's about it I think as far as I had planned.  Is there anything other than that that you would like worked on?  I'm not Facebook user, so I won't be able to check some things directly, nevertheless, if there's something you'd particularly like to have done, let me know and I'll see what my tuits look like.

**Comment by rizen** [comment]
Without you being able to actually test Facebook, no there's nothing else I can think of. I'll go ahead and merge all the pull requests so far.

**Comment by rizen** [comment]
Oh, yeah there is one other thing! Can you please update CHANGES.txt with all the changes you've made?

**Comment by paultcochrane** [comment]
Sure, no worries!

**Comment by paultcochrane** [comment]
Hi there!  I think I'm done with my pull requests.  It turned out that the whitespace patch fixed all of the `podchecker` warnings, so fixing those warnings didn't turn into a PR.  I don't see me having time to add more tests in the next couple of weeks, so if you want to cut a release go for it.  Many thanks for merging these PRs so quickly!

**Pull request merged**
